### PR TITLE
Correct a <td> to </td> closing tag

### PR DESCRIPTION
**Pull request by honestserpent**
line 140 of README.md

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@slnode test please

**Pull request merged**
