### PR TITLE
Update test information in readme

### PR DESCRIPTION
**Pull request by zbarbuto**
### Description

As mentioned in #197 the README information for testing is out of date. This adds brief instructions for how to run tests locally.

cc @jannyHou @crandmck @superkhau

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
@rmg CI seems to be hanging, PTAL?

**Comment by ssh24** [comment]
@slnode test please

**Comment by ssh24** [comment]
@zbarbuto Could you please **rebase** your branch?

**Comment by ssh24** [comment]
@slnode test please

**Comment by crandmck** [comment]
LGTM

**Comment by zbarbuto** [comment]
All done. Thanks guys.

**Comment by ssh24** [comment]
@slnode test please

**Pull request merged**
