### PR TITLE
Debug/transaction test

### PR DESCRIPTION
**Pull request by jannyHou**
Debug https://github.com/strongloop/loopback-connector-postgresql/pull/230

### CODE REVIEW

**Comment by jannyHou** [comment]
@slnode test please

**Comment by ssh24** [comment]
@slnode test please

**Comment by jannyHou** [comment]
The last commit won't work, client get destroyed if query returns error, haven't figured out how to create new client without running into race condition.

**Comment by ssh24** [comment]
@jannyHou Since postgres is fixed now, can this be closed?

**Pull request closed without merging**
