### PR TITLE
Allowed return metrics for INSERT operations

### PR DESCRIPTION
**Pull request by stev-0**
rowCount is also a relevant metric for INSERTS

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
Can you add a test to verify it works?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
@slnode test please

**Comment by stev-0** [comment]
Sorry, this was a bad idea - this should not be committed

**Pull request closed without merging**
