### PR TITLE
BIGSERIAL type support 

### PR DESCRIPTION
**Pull request by loryk**
### Description

Add support to  create fields with BIGSERIAL datatype.
This type will be added for options:
- genrated = true
- dataType = BIGINT/BIGSERIAL/BIG...

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by loryk** [comment]
Any news?

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@loryk , since we're landed your other PR, could you please rebase this PR? Thanks.

**Comment by loryk** [comment]
Try to rebase, and sims like do some mistake...
So, recreate request #392

**Pull request closed without merging**
