### PR TITLE
Fix: multiple foreign keys on same model

### PR DESCRIPTION
**Pull request by pharindoko**
### Description
Foreign Keys have not been separated correctly when statement will be executed in SQL.
If Multiple foreign keys are used this leads to an exception.

#### Related issues
#359 

### Checklist
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by pharindoko** [comment]
Hey, 
don`t know how I can lint it in another way. Used eslint as you did in your repository.
Please help. 

br,

florian

**Comment by pharindoko** [comment]
Hey,

please help me. 
I need to decide which ORM I can take for the current project.
Would like to take postgres, but then this small fix needs to be released.

Greetings,

Florian

**Comment by raymondfeng** [comment]
@pharindoko Thank you for the patch. Please first sign the CLA by click on https://cla.strongloop.com/agreements/strongloop/loopback-connector-postgresql.

**Comment by raymondfeng** [comment]
Please also amend the commit message as reported by our CI:
```
**
**  Linting commit logs
**
**  1 problems found:
**    eefa6dc - Fix: separated sql drop constraints statements corr: First line should be 50 characters or less (saw 56)
**
```

**Comment by pharindoko** [comment]
> @pharindoko Thank you for the patch. Please first sign the CLA by click on https://cla.strongloop.com/agreements/strongloop/loopback-connector-postgresql.

Hi, in the meantime I already signed it. 
But it doesn`t seem to get updated in the checks.

**Comment by pharindoko** [comment]
should I create a new Pull request ?
Seems like the checks won`t get refreshed....

**Comment by raymondfeng** [comment]
> should I create a new Pull request?

I don't think so.

Please amend the commit message per instructions at https://help.github.com/articles/changing-a-commit-message/

**Comment by pharindoko** [comment]
> > should I create a new Pull request?
> 
> I don't think so.
> 
> Please amend the commit message per instructions at https://help.github.com/articles/changing-a-commit-message/

Ok I amended the commit and the pull request got updated. Now the Commit Linter is happy.
Last thing is the CLA -> I did sign it.

**Comment by raymondfeng** [comment]
ok to test

**Comment by pharindoko** [comment]
> Can you please update the test to add multiple FKs?
> https://github.com/strongloop/loopback-connector-postgresql/blob/master/test/postgresql.autoupdate.test.js#L439

Hey @elv1s 
Can you do that ? I think you are hundred times faster than me... 💯 
I don`t wanna waste anyones time but this makes more sense in my eyes.
Don`t wanna bother you guys :-/

**Comment by pharindoko** [comment]
> > Can you please update the test to add multiple FKs?
> > https://github.com/strongloop/loopback-connector-postgresql/blob/master/test/postgresql.autoupdate.test.js#L439
> 
> Hey @elv1s
> Can you do that ? I think you are hundred times faster than me... 💯
> I don`t wanna waste anyones time but this makes more sense in my eyes. Don`t wanna bother you guys :-/

Tried my best to adapt the schema and  run 'npm test' but it fails for me.
A lot of tests worked but I far away of understanding what`s the issues in this test and why it doesn`t work. Here is what I tried to adapt...

```
      var orderTest_schema_v2 = {
        'name': 'OrderTest',
        'options': {
          'idInjection': false,
          'postgresql': {
            'schema': 'myapp_test',
            'table': 'order_test',
          },
          'foreignKeys': {
            'fk_ordertest_customerId': {
              'name': 'fk_ordertest_customerId',
              'entity': 'CustomerTest2',
              'entityKey': 'id',
              'foreignKey': 'customerId',
            },
            'fk_ordertest_customerTest3Id': {
              'name': 'fk_ordertest_customerTest3Id',
              'entity': 'CustomerTest3',
              'entityKey': 'id',
              'foreignKey': 'customer3Id',
            },
          },
        },
        'properties': {
          'id': {
            'type': 'String',
            'length': 20,
            'id': 1,
          },
          'customerId': {
            'type': 'String',
            'length': 20,
          },
          'customer3Id': {
            'type': 'String',
            'length': 20,
          },
          'description': {
            'type': 'String',
            'required': false,
            'length': 40,
          },
        },
      };

`
``

**Comment by elv1s** [comment]
@pharindoko thanks for finding this bug! The fix will need a test to verify. I'll work on updating the test to validate the fix.

**Comment by rmg** [comment]
@pharindoko the commit is attributed to `you@example.com` instead of an email address that is associated with your GitHub account so the CLA server has no way to verify that it is your contribution.

I'm not sure what your level of familiarity with git is or if you have any privacy concerns, but this GitHub Help article covers pretty much everything: https://help.github.com/articles/about-commit-email-addresses/

**Comment by pharindoko** [comment]
Thanks for the hint. I thought my mail will be used - wrong assumption. I will take care of it in the future and for now amend the commit ...

**Comment by pharindoko** [comment]
> @pharindoko the commit is attributed to `you@example.com` instead of an email address that is associated with your GitHub account so the CLA server has no way to verify that it is your contribution.
> 
> I'm not sure what your level of familiarity with git is or if you have any privacy concerns, but this GitHub Help article covers pretty much everything: https://help.github.com/articles/about-commit-email-addresses/

Ok. updated the commit. Now CLA hub accepts it.

**Comment by elv1s** [comment]
this was fixed in https://github.com/strongloop/loopback-connector-postgresql/pull/361

**Comment by dhmlau** [comment]
@elv1s 
> this was fixed in #361

Does this mean we should abandon this PR because the work is already done? Thanks.

**Comment by elv1s** [comment]
> @elv1s
> 
> > this was fixed in #361
> 
> Does this mean we should abandon this PR because the work is already done? Thanks.

Yes

**Comment by dhmlau** [comment]
@elv1s , thanks for confirming that. 
@pharindoko, with the above comment, I'm going to close your PR.  Thanks for your contributions anyway!

**Pull request closed without merging**
