### PR TITLE
GIN index support

### PR DESCRIPTION
**Pull request by abzarak**
### Description
simple edit on **migration.js** to add basic support of **GIN index**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by abzarak** [comment]
.ok\W+to\W+test.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by abzarak** [comment]
what should I do to get this passed?

**Pull request closed without merging**
