### PR TITLE
LIKE -> ILIKE

### PR DESCRIPTION
**Pull request by rus0000**
"ILIKE" case-insensitive, and more suitable for autocomplete comboboxes
http://www.postgresql.org/docs/9.4/static/functions-matching.html

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
Hi @rus0000, thank you for the pull request. In my opinion, this is a breaking change that also introduces inconsistency with the behaviour of other connectors (e.g. `memory` connector). I think it would be better to introduce a new operator instead. We already have `like` and `nlike`, so it should be relatively straightforward to implement `ilike` too.

Having said that, I'll let @raymondfeng review this patch as he is more familiar with the code base.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by rus0000** [comment]
https://github.com/strongloop/loopback-connector-postgresql/pull/93

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Pull request closed without merging**
