### PR TITLE
Enable Travis CI integration

### PR DESCRIPTION
**Pull request by bajtos**

### CODE REVIEW

**Comment by bajtos** [comment]
We need to land https://github.com/strongloop/loopback-connector-postgresql/pull/382 first to fix the build.

**Comment by emonddr** [comment]
What is causing these Jenkins failures? And the Travis failure?

**Comment by bajtos** [comment]
> What is causing these Jenkins failures? And the Travis failure?

@emonddr see my comment above:

> We need to land #382 first to fix the build.

**Comment by bajtos** [comment]
> [cis-jenkins] x64 && linux && nvm && dbs,10 — Failed! (023d66e)

This test failure is unrelated to my changes. I am going to ignore it and proceed to land this PR.

```
1) autoupdate
     foreign key constraint
       should create, update, and delete foreign keys:
   error: duplicate key value violates unique constraint "pg_namespace_nspname_index" (while running initial autoupdate)
    at Connection.parseE (node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (node_modules/pg/lib/connection.js:121:22)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Pull request merged**
