### PR TITLE
Added support for composite types

### PR DESCRIPTION
**Pull request by CSLTech**
### Description
Added support for composite types. I would however need a few pointers to as to how this could be efficiently testedin the current framework.

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by CSLTech** [comment]
There are some unforeseen bugs. Will re-open.

**Comment by b-admike** [comment]
@CSLTech Thank you for your contribution! I'll review your changes when I get a chance, and we can investigate the bugs together.

**Pull request closed without merging**
