### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by karanssj4**
## Checklist

👉 [Read and sign the CLA (Contributor License Agreement)](https://cla.strongloop.com/agreements/strongloop/loopback-connector-postgresql) 👈

- [ ] `npm test` passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style guide](https://loopback.io/doc/en/contrib/style-guide-es6.html)
- [ ] Commit messages are following our [guidelines](https://loopback.io/doc/en/contrib/git-commit-messages.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by dhmlau** [comment]
@slnode test please

**Comment by jannyHou** [comment]
Thanks @karanssj4 Some tests don't run probably due to the draft status, this change looks reasonable to me, so I changed it to "ready for review".

Let me trigger a test again.

**Comment by jannyHou** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
Related to: https://github.com/strongloop/loopback-next/issues/6020

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
CI on Travis (with various Node.js versions) are passing. The pending check is stuck because the machine is no longer available. I suggest to force merge this PR.

**Comment by dhmlau** [comment]
@karanssj4, thanks for your contribution. Your PR has landed! 🎉

**Pull request merged**
