### PR TITLE
Removed obsolete self.debug() function

### PR DESCRIPTION
**Pull request by ellenaua**
This is related to issue https://github.com/strongloop/loopback-connector-postgresql/issues/241

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ssh24** [comment]
@ellenaua Thank you for the patch. Could you please rebase your branch and fix the commit message? The commit message is too long:
```
**************************************************
**
**  Linting commit logs
**
**  1 problems found:
**    112677f - Added debugData so that it's possible to disable da: First line should be 50 characters or less (saw 63)
**
**************************************************
```

**Comment by ellenaua** [comment]
@ssh24 commit messages fixed

**Comment by ellenaua** [comment]
hm... maybe I should not remove PostgreSQL.prototype.debug function as it changes connector external api. I see that other connectors (loopback-connector-oracle) also declare debug() function. I can keep it for back-compatibility and for calling from outside

**Comment by ellenaua** [comment]
UPD: not all connectors have debug() function so it's not part of external api

**Comment by raymondfeng** [comment]
@ellenaua Please sign the CLA at https://cla.strongloop.com/agreements/strongloop/loopback-connector-postgresql

**Comment by ssh24** [comment]
@ellenaua Any updates on signing the CLA? https://cla.strongloop.com/agreements/strongloop/loopback-connector-postgresql

We are technically blocked with this PR until you sign it.

**Comment by ssh24** [comment]
@ellenaua Any update on signing the CLA?

**Comment by ssh24** [comment]
PR landed in https://github.com/strongloop/loopback-connector-postgresql/pull/275.

**Pull request closed without merging**
