### PR TITLE
Attempt at a crude error message when no id has been specified for model

### PR DESCRIPTION
**Pull request by stev-0**
I have had trouble (see [here](https://groups.google.com/forum/#!topic/loopbackjs/xlcVdTk8O4U) and [here](http://stackoverflow.com/questions/29746017/inserting-geometry-json-into-loopbackjs-model) with an insert into query in the postgresql connector. All other queries were working, but I didn't realise it was because I hadn't defined an id in my model. 

The error message was not very specific so this is an attempt to improve that situation. I realise it's fairly crude, happy to try and make it conform more to loopback standards, but I am a bit new to the project.

Failing this, is there a FAQ, or somewhere where this could be documented. I know it's obvious that a model backed by a database should have an id, but it's an easy mistake to make, and the fact that all other queries were working threw me for a while.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
The change LGTM, can you please wrap the line length at 80 characters?

I'll leave the final approval to @raymondfeng as he is maintaining this module.

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@stev-0 can you perhaps add a unit-test to verify the new behaviour?

**Comment by stev-0** [comment]
I am trying to figure out how the tests work - there is something in the wiki that says there is a test server - I wonder if I need the credentials for that? Or maybe it's possible to run the test db on my local postgres server?

I have also made the error a debug message so it's less intrusive - it stopped the server previously, which probably wasn't ideal.

**Comment by bajtos** [comment]
> I am trying to figure out how the tests work - there is something in the wiki that says there is a test server - I wonder if I need the credentials for that?

@raymondfeng can you please provide @stev-0 credentials for our test PostgreSQL server?

> Or maybe it's possible to run the test db on my local postgres server?

AFAIK, that's not possible now. I would like to have that ability too :+1:

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by 0candy** [comment]
@stev-0 @bajtos I'm not sure what happened to this PR but there is now 0 file changes. Can we close this PR?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
The pull request was sent from @stev-0's `master` branch, I am guessing the branch was changes since the pull request was opened. I am going to close this pull request.

@stev-0 If you have the code changes still available somewhere, then I recommend you to create a feature branch and open a new pull request from that new branch.

**Pull request closed without merging**
