### PR TITLE
chore: add package-lock.json

### PR DESCRIPTION
**Pull request by aharbis**
### Description

Commits the generated `package-lock.json` file.

#### Related issues

- connect to `none`

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by dhmlau** [comment]
I think there was some discussion about _not_ having the package.json in the connector repos.  @bajtos, could you please confirm? 

If so, I think the change should be to add a `.npmrc` file setting the package-lock to false. See https://github.com/strongloop/strong-remoting/blob/master/.npmrc

**Comment by aharbis** [comment]
That could make sense. I had checked issue and code history for the repo and did not see discussion for this, so went ahead and put the PR up.

If the decision is to not commit, I’m happy to submit the PR to add the `.npmrc` file.

**Comment by dhmlau** [comment]
Confirmed with @jannyHou, we don't want `package-lock.json` to be created. So if you could make the change to include the `.npmrc` file, that would be great. Thanks @aharbis!!

**Comment by aharbis** [comment]
Opened PR #391 to add `.npmrc`. Closing this PR.

**Pull request closed without merging**
