### PR TITLE
Return the updated entries in update query

### PR DESCRIPTION
**Pull request by Pistacchione**
#### Related issues

- return the updated entries in update statement (useful if you make a native SQL update query with `RETURNIG` command

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by Pistacchione** [comment]
.ok\W+to\W+test.

**Comment by Pistacchione** [comment]
.ok\W+to\W+test.

**Comment by Pistacchione** [comment]
.ok\W+to\W+test.

**Pull request closed without merging**
