### PR TITLE
Include the SSL Property

### PR DESCRIPTION
**Pull request by ataft**
#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ataft** [comment]
Fixes made and CLA signed

**Comment by b-admike** [comment]
@slnode test please

**Comment by b-admike** [comment]
@ataft Please squash your commits into one with the commit message of your first commit, and we should be able to land.

**Comment by ataft** [comment]
I can't figure out how to squash them. Can you just "Squash and Merge" when you do the merge? Thanks

**Comment by b-admike** [comment]
```

**Comment by b-admike** [comment]
@ataft No worries, I have squashed them for you. Here are the commands I ran for your future reference:
```
git remote add upstream https://github.com/strongloop/loopback-connector-postgresql
git fetch -p upstream
git rebase -i upstream/master
git push origin +patch-1
```
If you want detailed logs for the commands, I've put them in a gist [here](https://gist.github.com/b-admike/8f57ad84dca7e37bcd8c5f2cc91f5a9c). Thank you again for your contribution! 🎉

**Comment by b-admike** [comment]
@slnode test please

**Comment by b-admike** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by b-admike** [comment]
@slnode test please

**Comment by b-admike** [comment]
@slnode test please

**Comment by b-admike** [comment]
@slnode test please

**Comment by b-admike** [comment]
@slnode test please

**Comment by b-admike** [comment]
@slnode test please

**Comment by b-admike** [comment]
@slnode test please

**Pull request merged**
