### PR TITLE
Add ability to dynamically change schema based on request context

### PR DESCRIPTION
**Pull request by soloman1124**
The following shows our use case:

in `datasources.json`:
```
{
  "postgres": {
    "host": "postgres",
    "port": 5432,
    "url": "",
    "database": "",
    "password": "",
    "name": "postgres",
    "user": "",
    "connector": "postgresql",
    "contextSchema": "schema"
  }
}
```

and `mixins/schema-changes.js`
```
var LoopBackContext = require('loopback-context');

function getSubdomain(ctx) {
  var parts = ctx.req.headers.host.split('.');
  if (parts.length === 3) {
    return parts[0];
  }
  return null;
}

module.exports = function(model, debug) {
  model.beforeRemote('**', function(ctx, unused, next) {
    var schema = getSubdomain(ctx);
    if (schema) {
      LoopBackContext.getCurrentContext().set('schema', schema);
    }
    next();
  });
};
```

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@soloman1124 could you please add unit test to go with this PR? Also please fix your commit message as the commit linter is failing

**Comment by ssh24** [comment]
@soloman1124 Any updates on adding some units tests along with this PR?

**Comment by soloman1124** [comment]
@ssh24 sorry, I was just a bit busy recently, I will get into it ASAP.

**Comment by soloman1124** [comment]
@ssh24 as the tests requires some more involved setup. I might not have time to work on it. However, I have added in the description our intended use case (we want to use it in a multi tenant context, where each tenant sits on separated schema).  Hopefully, this can be considered part of the feature.

**Comment by dhmlau** [comment]
@soloman1124  could you also please sign the CLA? Thanks.
https://cla.strongloop.com/agreements/strongloop/loopback-connector-postgresql

**Comment by soloman1124** [comment]
Done

**Pull request closed without merging**
