### PR TITLE
[SEMVER-MAJOR] Drop Node 0.10 and 0.12 in package.json

### PR DESCRIPTION
**Pull request by dhmlau**
Drop Node 0.10 and 0.12 in package.json

### CODE REVIEW

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@slnode test please.
some server was down. kicking the test again.

**Comment by bajtos** [comment]
@dhmlau note that dropping support for Node.js 0.x versions is a breaking change that must be released in a new semver-major version (ideally together with https://github.com/strongloop/loopback-connector-postgresql/pull/312).

Other than that, I am fine with this change 👍

**Comment by dhmlau** [comment]
@bajtos , that's a good point.  Thanks for the reminder!  
We're having some issue with CI.  @b-admike is helping to look into the problem.

**Comment by dhmlau** [comment]
@b-admike , do you think this is good to merge?  the CI failure in `strong-agent` doesn't seem to be related.

**Comment by b-admike** [comment]
@dhmlau Yeah your PR has nothing to do with the failure, and we can merge it!

**Pull request merged**
