### PR TITLE
Add connection pool settings to README.md

### PR DESCRIPTION
**Pull request by honestserpent**
Add documentation to show how to add connection pool settings.
Now you can add min and max pool size and maximum client idle time.

#### Related issues
- #261 
- #185

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@honestserpent, Thanks for contributing.  Could you please sign the CLA?   https://cla.strongloop.com/agreements/strongloop/loopback-connector-postgresql

**Comment by honestserpent** [comment]
@dhmlau signed, should I do something else?

**Comment by dhmlau** [comment]
Yes. :) 
One of your commit messages is too long.  If you go to the Details for `Commit Linter` which has the red X, there's an error message: 
```
**  Linting commit logs
**
**  1 problems found:
**    28a543d - Add connection pool settings doc to README.md: line 3 longer than 72 characters.
```

**Comment by honestserpent** [comment]
@dhmlau mmm I actually don't get, is the title too long? It does look so, it's 41 chars.

**Comment by dhmlau** [comment]
It's the 3rd line.  `Add documentation and example to show how to set connection pool minimum`.
I just counted and there are exactly 72 characters. Maybe the 72 character long requirement is not inclusive.  Perhaps shorten a bit or make it to another line?

**Comment by honestserpent** [comment]
@dhmlau mmm i don't understand, I changed it and now it looks fine, but still doesn't work

**Comment by dhmlau** [comment]
@honestserpent , from what I see, your commit message is:
```
Add connection pool settings doc to README.md

Add documentation and example to show how to set connection pool minimum and maximum size and maximum client idle time
```
the commit message that is causing the error is `Add documentation and example....`

You can use `git commit --amend` to change the message.  Instructions can be found here: 
https://help.github.com/articles/changing-a-commit-message/

Hope it helps!

**Comment by honestserpent** [comment]
@dhmlau that's interesting. I actually edited the readme directly in github, you have any idea on how i should do?

**Comment by dhmlau** [comment]
@honestserpent, I'm not sure how / if we can do it from the web site.  A few options:
1. If you're familiar with git command, use the instruction I sent you above
2. Use GitHub Desktop (I haven't used it before, so you might wanna explore whether it's possible)
3. Grant me access to your repo and I can fix it for you.
https://github.com/blog/2247-improving-collaboration-with-forks

**Comment by ssh24** [comment]
@honestserpent I have rebased the branch for you and fixed your commit message error. Please pull to get the latest.

@slnode test please

**Comment by honestserpent** [comment]
@ssh24 thanks!

**Pull request merged**
