### PR TITLE
Changes in PostgreSQL datatypes

### PR DESCRIPTION
**Pull request by yellowiscool**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@yellowiscool thank you for the pull request. I am not familiar enough with this project, I'll let @raymondfeng to review your patch.

However, I would like to point out a possible backwards compatibility issue. IIUC, this change is forcing all users of the PostgreSQL connector to modify their database schema to use these new types, at least when they run auto-update/auto-migrate script. 

Perhaps we can add a flag (connector/datasource setting) to allow the users to decide whether they want the old or the new mapping?

**Comment by kadim** [comment]
Why not JSONB? It can be indexed!

**Comment by TinOo512** [comment]
@raymondfeng can we have update on this ? If I read the postgresql documentation (http://www.postgresql.org/docs/9.1/static/datatype-character.html) there is no benefits to use `character varying` with a specified length.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by tobernguyen** [comment]
Why this pull request take so long? Please review and accept this so this problem will be fixed.
https://github.com/strongloop/loopback-component-passport/issues/84

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
Can you add some tests to verify your changes and prevent regressions in the future?

**Comment by archenroot** [comment]
Not sure if relevant to put here, but as it refers to new data types, better do, we have also hstore now, similar to redis key-value fundamentally:
https://github.com/strongloop/loopback-connector-postgresql/issues/232

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
