### PR TITLE
feat(app): Add a createDatabase option to automatically create the database

### PR DESCRIPTION
**Pull request by thaiat**
I have added a createDatabase option to automatically create the database when it does not exist, as per the mysql connector.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by thaiat** [comment]
Second commit deals with automigrate situation where if you need to drop a dependent TABLE, postrgres requires the CASCADE keyword

**Comment by 0candy** [comment]
@thaiat Can you add some unit tests to verify your changes?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
@thaiat Could you please rebase your code? Please keep in mind there will be merge conflicts on `lib/postgresql.js` file. Also please add some unit tests according to the patch to prevent future regression.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ssh24** [comment]
Closing this PR as it is stale and has been no response. Feel free to reopen a new one.

**Pull request closed without merging**
