### PR TITLE
Fix #123: Set default value during autoupdate.

### PR DESCRIPTION
**Pull request by STRML**
This is a mergeable update to #153 that also respects dbDefault.

Unfortunately it is not clear how to run tests on this repository.

### CODE REVIEW

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
LGTM

**Comment by rmg** [comment]
Had to fix a problem on the Windows environment.

@slnode test please

**Comment by superkhau** [comment]
test please

**Comment by 0candy** [comment]
@STRML Would you mind rebasing this so we can get it merged?  Thanks!

**Comment by STRML** [comment]
Rebased, building now.

**Comment by superkhau** [comment]
@STRML Thanks for the contribution! ;)

**Pull request merged**
