### PR TITLE
Index implementation

### PR DESCRIPTION
**Pull request by Klowner**
I'm fairly certain this is a mostly functional solution to strongloop#47

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
@Klowner Thank you for the patch. Would you please add some test cases? If some DB set up is required, please provide the SQL scripts so that we can set up the test fixtures.

**Comment by Klowner** [comment]
@raymondfeng sure thing, I'll get right on that!

**Comment by Klowner** [comment]
@raymondfeng unit tests are updated/added.

**Comment by Klowner** [comment]
Let me know if there's anything else I can assist with!

**Comment by grosem** [comment]
:+1:

**Comment by eroh92** [comment]
Would be great to have this pull request accepted!

**Comment by raymondfeng** [comment]
Great. I'll look into it after #75. If one of you can rebase it on top of #75, it would be appreciated.

**Comment by Klowner** [comment]
Looks like there are a couple minor (at least at first glance) rebase conflicts. I'll deal with them ASAP.

**Comment by Klowner** [comment]
yeeeah, this is a mess

**Comment by raymondfeng** [comment]
Most of related code are now in https://github.com/strongloop/loopback-connector-postgresql/blob/master/lib/migration.js. Maybe a manual copy/paste merge is simpler.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by Klowner** [comment]
Rebased onto master, related unit tests are successful, hopefully this is all good to go.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
ok to test

**Pull request merged**
