### PR TITLE
Use canonical index name when dropping

### LINKED ISSUE #354: Using multiple schemas getting error: relation "index_name" already exists
I am using multiple schemas, 'public' for production and 'dev' for development in the same database
when I run a migration after modifying a few indexes, I get this error

`error: relation "index_name_idx" already exists`

this index does not exist on 'dev' schema but on 'public' while im using the 'dev' schema

after adding debug log `DEBUG=loopback:connector:* npm start`, i found out that drop index query does not have a schema name
`DROP INDEX "index_name_idx"`

It should be `DROP INDEX "schema_name"."index_name_idx"`

its a small fix if you guys can help out

thanks

### PR DESCRIPTION
**Pull request by jlawrencecfm**
Should fix #354

### Description
Add the schema name to index name when dropping indices, otherwise the migration script can fail 
due to not being able to find the index, or not being able to re-create the index because it never dropped it.

#### Related issues

- connect to 354

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

Sadly I don't have time to write tests or check the style (I copied the surrounding code style, so should be fine?), but it shouldn't break any existing tests.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by elv1s** [comment]
The change looks good. It looks like the tests haven't kicked off in pipeline though. Maybe another maintainer can trigger them?

Also please write a test to ensure this doesn't regress.

**Comment by dhmlau** [comment]
@slnode test please

**Comment by elv1s** [comment]
@jlawrencecfm can you please take a look at the test failures. You should be able to run the tests locally by following https://github.com/strongloop/loopback-connector-postgresql#running-tests

**Comment by jlawrencecfm** [comment]
I've ran the test locally and all tests are passing, this must be a problem with your CI setup?

I can't click the "Details" button next to the test failure without giving strongloop oauth access to my company's teams and organisations which I am not authorised to do.

**Comment by elv1s** [comment]
@slnode test please

**Comment by bajtos** [comment]
FWIW, I think this is a good place where to add new tests:
https://github.com/strongloop/loopback-connector-postgresql/blob/master/test/postgresql.autoupdate.test.js

**Comment by jlawrencecfm** [comment]
Regression test added.

**Comment by emonddr** [comment]
@jlawrencecfm , thank you for adding the test case. The `Commit Linter` is having an issue with a commit message. If you can please fix it. Thx.

image
Click on `Details`
and view the log. You will see the error:

image

**Comment by jannyHou** [comment]
@slnode test please

**Comment by emonddr** [comment]
@slnode test please

**Comment by emonddr** [comment]
image

npm test is failing with node v6.17.1 in Jenkins though I cannot reproduce this locally on my laptop with `master` branch or `patch-1` branch using same version of node.

**Comment by emonddr** [comment]
@rmg , if you could please help us understand the specific failure and why the same failure doesn't occur in the other tests. Thank you so much. :)

**Comment by dhmlau** [comment]
I think I've seen it before that the error is intermittent.  Let's kick off the test again.
@slnode test please

**Comment by jlawrencecfm** [comment]
There's an intermittently failing test in postgresql.test.js -> lazyConnect -> should skip connect phase (lazyConnect = true)

```
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (loopback-connector-postgresql/test/postgresql.test.js)
Connection fails: Error: connect ECONNREFUSED 127.0.0.1:4
It will be retried for the next request.
```

**Comment by emonddr** [comment]
hmm the error I was seeing consistently yesterday (we ran the build 3 times) was 👍 
image

Not sure why it is working today.

**Comment by emonddr** [comment]
@slnode test please

**Pull request merged**
